database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "1234"
  dbname: "mdr_backend"
  sslmode: "disable"
jwt:
  secret: "your-secret-key"
  ttl: 21600          # 6小时 (秒)
  remember_me_ttl: 2592000  # 30天 (秒)
email:
  smtp_host: "smtp.qq.com"
  smtp_port: 465
  smtp_user: "2972853299@qq.com"
  smtp_password: "ehlcioyseprzdghj"  # 不是QQ密码，而是开启SMTP服务时获得的授权码
  from_email: "2972853299@qq.com"